name: Release CI

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compute lowercase owner
        run: |
          echo "OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Extract release version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LOWER }}/robokop-frontend:cache
          cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LOWER }}/robokop-frontend:cache,mode=max
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/robokop-frontend:latest
            ghcr.io/${{ env.OWNER_LOWER }}/robokop-frontend:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            VITE_DEPLOYMENT=${{ secrets.VITE_DEPLOYMENT }}
